# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aí ta na disney
email: marcus.teres@gmail.com
email_label: email
description:  Um blog para o dia que eu tiver coragem para escrever algo.
mensagem: Juro que vou fazer uma pagina aqui.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mteres.github.io" # the base hostname & protocol for your site
twitter_username: teres93
github_username:  MTeres

# Build settings
markdown: kramdown
